[tool.poetry]
name = "test2"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.0"

<<<<<<< HEAD
=======

>>>>>>> 4ff00fa (test2)
[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
<<<<<<< HEAD
select = ["ALL"]
ignore = ["RUF001", "T201"]

fixable = ["ALL"]
unfixable = []
exclude = [".git", ".ruff_cache"]

line-length = 79
target-version = "py310"
=======
select=["ALL"]
unfixable=[]
exclude=[".git", ".ruff_cache"]

line-length=79
target-version="py310"
>>>>>>> 4ff00fa (test2)
